version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all dependency updates into one PR
    groups:
      npm:
        patterns:
          - "*"
