version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Group all dependency updates into one PR
    groups:
      all:
        patterns:
          - "*"
